services:
  mysql:
    image: mysql:8.0
    container_name: mysql-posada-volumes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: posada_db
      MYSQL_USER: posada_user
      MYSQL_PASSWORD: posada_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - posada-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "posada_user", "-pposada_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  posada-app:
    image: lup1ta/posada-api:1.0.3
    container_name: posada-app
    platform: linux/amd64
    environment:
      QUARKUS_DATASOURCE_USERNAME: posada_user
      QUARKUS_DATASOURCE_PASSWORD: posada_password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/posada_db
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - posada-network

volumes:
  mysql-data:

networks:
  posada-network:
    driver: bridge